CREATE DATABASE INSTACART_DB
ON PRIMARY (NAME = 'INSTACART_data', FILENAME = 'C:\INSTACART\INSTACART_data.mdf', 
SIZE = 512MB, FILEGROWTH = 128MB)
LOG ON (NAME = 'INSTACART_log', FILENAME = 'C:\INSTACART\INSTACART_log.ldf', 
SIZE = 128MB, FILEGROWTH = 32MB);